name: Commit Stage
on:
  push:
  schedule: # Every Tuesday
    - cron: '0 0 * * 1'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: kadras-io/workflow-java-base
  VERSION: ${{ github.sha }}

jobs:
  package:
    name: Package and Publish
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.0.5

      - name: Check out source code
        uses: actions/checkout@v3.5.2

      - name: Log into container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Compute artifact version
        run: |
          echo "VERSION=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      
      - name: Build and publish container image
        uses: docker/build-push-action@v4.0.0
        with:
          context: image
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      
      - name: OCI image vulnerability scanning
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          format: 'sarif'
          output: 'trivy-results-oci-image.sarif'

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: 'trivy-results-oci-image.sarif'

      - name: Sign image
        run: |
          cosign sign --yes "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
